default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: pet_hotel

# test: &test
#   <<: *default
#   database: movies_test

production: